version: '3.2'
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
    - :9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - /data/compose/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    - /data/compose/prometheus_data:/etc/prometheus/data:rw
    depends_on:
    - cadvisor
  cadvisor:
    image: gcr.io/cadvisor/cadvisor:latest
    container_name: cadvisor-controller
    ports:
      - :8080
    volumes:
      - /:/rootfs:ro
      - /var/run:/var/run:rw
      - /sys:/sys:ro
      - /var/lib/docker/:/var/lib/docker:ro
    depends_on:
      - redis
  redis:
    image: redis:latest
    container_name: redis
    ports:
      - :6379
  portainer:
    image: portainer/portainer-ce:alpine
    container_name: portainer-controller
    command: -H unix:///var/run/docker.sock
    ports:
      - "32772:9000"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "/data/compose/portainer:/data"
    restart: always
  watchtower:
    container_name: watchtower-container
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
