version: "3.9"
services:
  homer:
    container_name: homer
    image: b4bz/homer:latest
    volumes:
      - /data/compose/homer:/www/assets
    ports:
      - 34250:8080
    user: 1000:1000 # 1000 default
    environment:
      - INIT_ASSETS=1 # default
      - TZ=America/Chicago