---
version: '3'
services:
  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge-ums
    hostname: deluge-ums
    domainname: dbotz.molovestoshare.com
    volumes:
      - /data/compose/deluge:/config
      - /home/monash/Backup_Disk/media/downloads:/downloads
    environment:
      - PUID=1000
      - PGID=1000
      - HOME=/config
      - WEB_PORT=8112
      - TZ=America/Chicago
    ports:
      - 8112:8112
      - 6881:6881/udp
    restart: unless-stopped
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr-ums
    domainname: prowlarr.molovestoshare.com
    environment:
        - PUID=1000
        - PGID=1000
        - TZ=America/Chicago
    volumes:
      - /data/compose/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest # DockerHub mirror flaresolverr/flaresolverr:latest
    container_name: flaresolverr-ums
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=America/Chicago
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr-ums
    hostname: radarr
    domainname: radarr.molovestoshare.com
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/Chicago"
    volumes:
      - /data/compose/radarr:/config
      - /home/monash/Backup_Disk/media/movies:/movies
      - /home/monash/Backup_Disk/media/downloads:/downloads
    ports:
      - 7878:7878
    restart: unless-stopped
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr-ums
    hostname: sonarr
    domainname: sonarr.molovestoshare.com
    environment:
      - PUID=1000
      - PGID=1000
      - TZ="America/Chicago"
    volumes:
      - /data/compose/sonarr:/config
      - /home/monash/Backup_Disk/media/tv:/tv
      - /home/monash/Backup_Disk/media/downloads:/downloads
    ports:
      - 8989:8989
    restart: unless-stopped
