version: '3.9'
services: 
  pihole:  # For DHCP it is recommended to remove these ports and instead add: network_mode: "host"
    container_name: pihole
    image: pihole/pihole:latest
    network_mode: "host"
    ports:
      - :53
      - :67 # Only required if you are using Pi-hole as your DHCP server
      - 32823:80
    environment:
      TZ: "America/Chicago"
      WEBPASSWORD: '~Z0vJE8Q_S4wezp6r@)u>9:52N/T\lM1'
      #DNSMASQ_LISTENING: all # optional but nrcessary for certain conditions, rtfm
    volumes: # Volumes store your data between container upgrades
      - '/data/compose/pihole:/etc/pihole'
      - '/data/compose/pihole/etc-dnsmasq.d:/etc/dnsmasq.d'
    labels:
      com.example.hypervisor: "controller"
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: unless-stopped

  cadvisor:
    container_name: cadvisor
    image: google/cadvisor:latest
    privileged: true
    ports:
      - 2200:2200
    command:
      - "--housekeeping_interval=60s"
      - "--docker_only=false"
      - "--disable_metrics=percpu,sched,tcp,udp,disk,diskIO,accelerator,hugetlb,referenced_memory,cpu_topology,resctrl"
    devices:
      - /dev/kmsg:/dev/kmsg
    volumes:
      - /var/lib/docker/:/var/lib/docker:ro
      - /dev/disk/:/dev/disk:ro
      - /sys:/sys:ro
      - /var/run:/var/run:rw
      - /:/rootfs:ro
      - /sys/fs/cgroup:/cgroup:ro
      - /etc/machine-id:/etc/machine-id:ro
      - /etc/localtime:/etc/localtime:ro
    expose:
      - 8080
    labels:
      com.example.hypervisor: "controller"
    restart: unless-stopped

  dozzle:
    container_name: dozzle
    image: amir20/dozzle:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 8080:8080
    environment:
      DOZZLE_LEVEL: trace
    healthcheck:
      test: [ "CMD", "/dozzle", "healthcheck" ]
      interval: 3s
      timeout: 30s
      retries: 3
      start_period: 60s
    labels:
      com.example.hypervisor: "controller"
    restart: unless-stopped

  portainer:
    image: portainer/portainer-ce:latest
    container_name: portainer-controller
    restart: unless-stopped
    environment:
      TZ: "America/Chicago"
    security_opt: ["no-new-privileges=false"]
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /opt/portainer-controller_data:/data
    labels:
      com.example.hypervisor: "controller"  
    restart: unless-stopped