---
version: '3.9'
services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrunt
    hostname: qbittorrunt
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/Chicago
      - WEBUI_PORT=MATCH-PORT
    volumes:
      - /data/compose/qbittorrent/data:/config
      - /data/compose/qbittorrent/qBittorrent.conf:/config/qBittorrent/qBittorrent.conf
      - /home/monash/Backup_Disk/media/downloads:/downloads
    ports:
      - MATCH-PORT:MATCH-PORT
      - :6881
      - :6881/udp
    restart: unless-stopped
