version: '3.9'
services:
  protonvpn:
    container_name: protonvpn
    hostname: protonvpn
    domainname: protonvpn.yourdomain.righthurr
    environment:
      PROTONVPN_USERNAME: <yo-shhhheeeeeiiiiiittt>
      PROTONVPN_PASSWORD: <yo-shhhheeeeeiiiiiittt>
      PROTONVPN_SERVER: RANDOM
      PROTONVPN_TIER: 0
      PROTONVPN_FAIL_THRESHOLD: 3
    # Always use semver tags, avoid using tag latest!
    image: ghcr.io/tprasadtp/protonvpn:latest
    restart: unless-stopped
    networks:
      - pihole_default
      - vpn-traffic
    cap_add:
      - NET_ADMIN
    devices:
      - /dev/net/tun:/dev/net/tun
    # Expose pyload container's port here!
    expose:
      - 3579
      - 7878
      - 8191
      - 8181
      - 8989
      - 51413
  flaresolverr:
    depends_on:
      - protonvpn
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr-jackett-helper
    hostname: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Amcerica/Chicago
    networks:
      - pihole_default
      - vpn-traffic
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
  jackett:
    depends_on:
      - protonvpn
    hostname: jackett
    domainname: jackett.yourdomain.righthurr
    container_name: jackett-container
    environment:
      AUTO_UPDATE: "true"
      TZ: "America/Chicago"
      PGID: "1000"
      PUID: "1000"
    image: lscr.io/linuxserver/jackett:latest
    networks:
      - pihole_default
      - vpn-traffic
    ports:
      - "${PORT:-9117}:9117"
  transmission:
    depends_on:
      - protonvpn
    container_name: transmission-vpn-container
    hostname: transmission
    domainname: transmission.yourdomain.righthurr
    environment:
      TZ: "America/Chicago"
      PGID: "1000"
      PUID: "1000"
    image: lscr.io/linuxserver/transmission:latest
    networks:
      - pihole_default
      - vpn-traffic
    ports:
      - "${PORT:-9091}:9091"
      - "${PORT:-51413}:51413"
    restart: unless-stopped
    volumes:
      - /data/compose/transmission:/config
      - /home/monash/Backup_Disk/media/downloads:/downloads/:rw

networks:
  pihole_default:
    external: true
  vpn-traffic:
    internal: true
