---
version: '3'
services:
  plex:
    image: linuxserver/plex:latest
    container_name: plex-ums
    hostname: plex-ums
    domainname: plex.molovestoshare.com
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ="America/Chicago"
      - runtime=nvidia
      - PLEX_CLAIM= # Generate new claim codes here: https://www.plex.tv/claim/
    volumes:
      - /data/compose/plex/config:/config
      - /data/compose/plex/transcodes:/transcodes
      - /home/monash/Backup_Disk/media/tv:/tv
      - /home/monash/Backup_Disk/media/movies:/movies
      - /home/monash/Backup_Disk/media/videos:/videos
      - /home/monash/Backup_Disk/media/audiobooks:/music
    ports:
      - 32400:32400
      - :1900/udp
      - :3005
      - :5353/udp
      - :8324
      - :32469
      - :32410/udp
      - :32412/udp
      - :32413/udp
      - :32414/udp
    restart: unless-stopped
