version: "3.9"
services:
  #MySQL Database image
  db:
    image: mysql:8.0
    container_name: wbdb
    restart: unless-stopped
    environment:
      - MYSQL_DATABASE=_
    volumes: 
      - /data/compose/dbdata:/var/lib/mysql
    command: '--default-authentication-plugin=mysql_native_password'
  
  wordpress:
    depends_on: 
      - db
    image: wordpress:5.1.1-fpm-alpine
    container_name: wordpress
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db:3306
      - WORDPRESS_DB_USER=
      - WORDPRESS_DB_PASSWORD=''
      - WORDPRESS_DB_NAME=
    volumes:
      - /data/compose/wordpress:/var/www/html


  webserver:
    depends_on:
      - wordpress
    image: nginx:1.15.12-alpine
    container_name: wpwebserver
    restart: unless-stopped
    ports:
      - :80
    volumes:
      - /data/compose/wordpress:/var/www/html
      - /data/compose/nginx-conf:/etc/nginx/conf.d
      - /data/compose/certbot-etc:/etc/letsencrypt
